docs(README): fix webpack 2 compatibility
eldh/yaml-frontmatter-loader pull request #4
Opened 2017-04-16 10:41 UTC by simon04

2017-04-17 00:18 UTC, michael-ciniawsky requested changes

2017-04-17 00:18 UTC, michael-ciniawsky commented on README.md
>  ## Usage
`<h2 align="center"><a href="https://webpack.js.org/concepts/loaders/">Usage</a></h2>`

2017-04-17 00:18 UTC, michael-ciniawsky commented on README.md
>  # yaml-frontmatter-loader for webpack
```
[![npm][npm]][npm-url]
[![node][node]][node-url]
[![deps][deps]][deps-url]
[![tests][tests]][tests-url]
[![coverage][cover]][cover-url]
[![chat][chat]][chat-url]

<div align="center">
  <img width="200" height="200"
    src="<!--  YAML Logo  or delete ;) -->">
  <a href="https://github.com/webpack/webpack">
    <img width="200" height="200"
      src="https://webpack.js.org/assets/icon-square-big.svg">
  </a>
  <h1>YAML Formatter Loader</h1>
</div>
```

2017-04-17 00:18 UTC, michael-ciniawsky commented on README.md
>  ``` javascript
**webpack.config.js**
\```javascript => \```js

```js
module.exports = {
  module: {
    rules: [
      {
         test: /\.md$/,
         use: [ 'json-loader', 'yaml-fontmatter-loader' ]
      }
    ]
  }
}
```

2017-04-17 00:18 UTC, michael-ciniawsky commented on README.md
**file.md**
```md
### Example File
```

2017-04-17 00:18 UTC, michael-ciniawsky commented on README.md
```diff
- ## LICENSE
```

```
[npm]: https://img.shields.io/npm/v/yaml-fontmatter-loader.svg
[npm-url]: https://npmjs.com/package/yaml-fontmatter-loader

[node]: https://img.shields.io/node/v/yaml-fontmatter-loader.svg
[node-url]: https://nodejs.org

[deps]: https://david-dm.org/webpack-contrib/yaml-fontmatter-loader.svg
[deps-url]: https://david-dm.org/webpack-contrib/yaml-fontmatter-loader

[tests]: http://img.shields.io/travis/webpack-contrib/yaml-fontmatter-loader.svg
[tests-url]: https://travis-ci.org/webpack-contrib/yaml-fontmatter-loader

[cover]: https://codecov.io/gh/webpack-contrib/yaml-fontmatter-loader/branch/master/graph/badge.svg
[cover-url]: https://codecov.io/gh/webpack-contrib/yaml-fontmatter-loader

[chat]: https://badges.gitter.im/webpack/webpack.svg
[chat-url]: https://gitter.im/webpack/webpack
```

2017-04-17 00:18 UTC, michael-ciniawsky commented on README.md
>  ## Installation
`Installation` => `Install`

2017-04-28 18:32 UTC, simon04 commented
Thanks for your comments. The many changes were rather confusing to carry over, though. I hope to not have missed anything.

2017-04-28 19:23 UTC, michael-ciniawsky approved these changes
Thx 👍  very much 😛

2017-04-28 19:23 UTC, merged